### PR TITLE
[WIP] Parsec-ify

### PR DESCRIPTION
**Pull request by hexylena**
Convert the scripts to a Chado "library" and then CLI scripts like parsec/arrow :)

Needs a better CLI name than `cc` since that's used for compiling. Thoughts?

Note: this probably also breaks py2 stuff, I switched to py3 a while back.

### CODE REVIEW

**Review by abretaud — APPROVED** [review]

**Comment by abretaud** [comment]
Greaaaat! Thanks for working on this!
For the name... well, it's hard to find a good one as usual :)
There could be some ideas there: https://en.wikipedia.org/wiki/Japanese_tea_ceremony
`chakin`? `chanoyu`?
(`chaton` would be fun too 🐈 🐈 🐈 )

**Comment by hexylena** [comment]
chakin works for me, probably the easiest for everyone to pronounce / remember. I'll update that shortly. Thanks for the ideas :)

**Comment by hexylena** [comment]
By the way, the `parsec -> galaxyxml` can happen for the apollo / chado tools as well, just again, not sure how useful it will be.

**Comment by abretaud** [comment]
Yes, I don't know if I would really use them, but galaxy tools would be fun!

**Comment by hexylena** [comment]
@abretaud ok, done. Ready for re-review / merge. Would you mind configuring read-the-docs support for this project?

**Comment by abretaud** [comment]
Cool!
Looking at the code I think there are a few `parsec` that should be renamed to `chakin`
read-the-docs is configured now: http://python-chado.readthedocs.io

**Comment by hexylena** [comment]
Good call, fixed.

**Comment by abretaud** [comment]
Yeeha!
I'll see if I can transfer this repo to GGA organization, it would be better there I think

**Pull request merged**
